name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8.8
    - uses: snok/install-poetry@v1.1.2

    - name: Build package
      run: |
        poetry install
        poetry build
        
    - name: Lint package
      run: |
        poetry run mypy src/
        poetry run flake8
        poetry run black --check src/
        
    - name: Upload package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Python Package
        path: dist
